// Generated by scripts/sync-conformance.mjs from packages/client/conformance.
// Do not edit; re-run the sync script to adopt a new core fixture pin.
export const CONFORMANCE_PARLE_VERSION = "2026-07-07";

export type ConformanceTokenClass = {
  name: string;
  prefix: string;
  secret: boolean;
  shape: string;
  redaction_pattern: string;
  redact_with: string;
  description: string;
};

export const CONFORMANCE_TOKEN_CLASSES: ConformanceTokenClass[] = [
  {
    "name": "participant_bearer",
    "prefix": "prt_",
    "secret": true,
    "shape": "prt_<43 base64url characters>",
    "redaction_pattern": "prt_[A-Za-z0-9_-]{43}",
    "redact_with": "prt_<redacted>",
    "description": "Room-scoped participant bearer."
  },
  {
    "name": "agent_bearer",
    "prefix": "parle_agt_",
    "secret": true,
    "shape": "parle_agt_<43 base64url characters>",
    "redaction_pattern": "parle_agt_[A-Za-z0-9_-]{43}",
    "redact_with": "<redacted-token>",
    "description": "Room-bound agent bearer."
  },
  {
    "name": "agent_session_credential",
    "prefix": "parle_ses_",
    "secret": true,
    "shape": "parle_ses_<43 base64url characters>",
    "redaction_pattern": "parle_ses_[A-Za-z0-9_-]{43}",
    "redact_with": "<redacted-token>",
    "description": "Live agent-session credential."
  },
  {
    "name": "invite_secret",
    "prefix": "parle_inv_",
    "secret": true,
    "shape": "parle_inv_<43 base64url characters>",
    "redaction_pattern": "parle_inv_[A-Za-z0-9_-]{43}",
    "redact_with": "<redacted-token>",
    "description": "Invite claim secret."
  },
  {
    "name": "human_session_cookie",
    "prefix": "parle_sess_",
    "secret": true,
    "shape": "parle_sess_<43 base64url characters>",
    "redaction_pattern": "parle_sess_[A-Za-z0-9_-]{43}",
    "redact_with": "<redacted-token>",
    "description": "Human session cookie value."
  }
];
